version: '2.4'

services:
  mail:
    image: ayudadigital/gp-mail:2.0.1
    volumes:
      - ./data/var/spool/postfix:/var/spool/postfix
    ports:
      - 0025:0025

networks:
    default:
      external:
        name: platform_services
