version: '3.7'

services:
  mail:
    image: teecke/gp-mail:0.3.0
    volumes:
      - ./data/var/spool/postfix:/var/spool/postfix
    ports:
      - 0025:0025

networks:
    default:
      external:
        name: platform_services
