version: '2.4'

services:
  passboltdb:
    image: mariadb:10.3
    env_file:
      - mysql.env
    volumes:
      - ./data/passboltdb/var/lib/mysql:/var/lib/mysql

  passbolt:
    image: ayudadigital/gp-passbolt:2.0.1
    ports:
      - 4004:80
    tty: true
    depends_on:
      - passboltdb
    env_file:
      - passbolt.env
    volumes:
      - ./data/passbolt/var/www/passbolt/config/gpg:/var/www/passbolt/config/gpg
      - ./data/passbolt/var/www/passbolt/webroot/img/public:/var/www/passbolt/webroot/img/public
    tmpfs:
      - /run
    command: ["/usr/bin/wait-for.sh", "db:3306", "-t", "60", "--", "/docker-entrypoint.sh"]

networks:
    default:
      external:
        name: platform_services

volumes:
  passboltdb: