version: '2.4'

services:
  sonarqube:
    image: ayudadigital/gp-sonarqube:2.0.0
    ports:
      - 4002:9000
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonardb:5432/sonar
      - SONARQUBE_JDBC_USERNAME=${POSTGRES_USER}
      - SONARQUBE_JDBC_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./data/sonarqube/opt/sonarqube/conf:/opt/sonarqube/conf
      - ./data/sonarqube/opt/sonarqube/data:/opt/sonarqube/data
      - ./data/sonarqube/opt/sonarqube/extensions:/opt/sonarqube/extensions
      - ./data/sonarqube/opt/sonarqube/lib/bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    ulimits:
      nproc: 65536
      nofile: 
        soft: 65536
        hard: 65536

  sonardb:
    image: postgres:12.1
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./data/sonardb/var/lib/postgresql/data:/var/lib/postgresql/data

networks:
    default:
      external:
        name: platform_services

volumes:
  postgresql:
  postgresql_data:
