version: '3.7'

services:
  jenkins-dind:
    image: ayudadigital/gp-jenkins:2.0.0
    ports:
      - 4001:8080
      - 5001:5000
    volumes:
      - ./data/var/jenkins_home:/var/jenkins_home
      - docker:/var/lib/docker
    privileged: true

networks:
    default:
      external:
        name: platform_services

volumes:
  docker:
