version: '3.7'

services:
  statics:
    image: ayudadigital/gp-nginx:2.0.0
    ports:
      - 8002:80
    volumes:                                                                     
      - ./data/usr/share/nginx/html:/usr/share/nginx/html:ro
    restart: unless-stopped
      
networks:
    default:
      external:
        name: platform_products
