version: '3.7'

services:
  webapp:
    image: ayudadigital/gp-php:2.0.0
    ports:
      - 8001:80
    volumes:
      - ./data/var/www/html:/var/www/html:ro
    restart: unless-stopped
      
networks:
    default:
      external:
        name: platform_products
