version: '3.4'

services:
  nexus:
    image: sonatype/nexus:oss
    ports:
      - 4003:8081
    volumes:                                                                     
      - sonatype-work:/sonatype-work
      
networks:
    default:
    
      external:
        name: platform_services

volumes:
  sonatype-work:
