version: '3.4'

services:
  nexus:
    image: teecke/gp-nexus:0.3.1
    ports:
      - 4003:8081
    volumes:
      - ./data/nexus-data:/nexus-data
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      
networks:
    default:
      external:
        name: platform_services